spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: your_jwt_secret_key_here_make_it_very_long_and_secure_in_production
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8080

logging:
  level:
    com.banking: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 